name: Build macOS

on:
  push:
    tags:
      - "darwin-v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Create output directory
        run: mkdir -p build/darwin/${{ matrix.arch }}

      - name: Build plugin
        run: |
          CGO_ENABLED=1 GOOS=darwin GOARCH=${{ matrix.arch }} go build -buildmode=c-shared -o build/darwin/${{ matrix.arch }}/plugin.dylib plugin.go

      - name: Pack tar.gz
        run: |
          cd build/darwin/${{ matrix.arch }}
          tar -czf ../../../darwin-${{ matrix.arch }}.tar.gz *

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.gz
